### ISSUE TITLE
Uninitialized constant is possible cause of compilation issues 

### ISSUE THREAD

**Issue by n-wbrown** [pcdshub/lcls-twincat-pmps#13]
An uninitialized variable found [here](https://github.com/pcdshub/lcls-twincat-pmps/blob/376bbb18629c6717be13b56ca973173b7d207cf5/lcls-twincat-pmps/Library/GVLs/PMPS_GVL.TcGVL#L40) may be causing some issues. While the code can normally be built in normal conditions, builds preempting a "login w/ change" fail. Pihl speculates that this could be a potential cause of the issue.
 
`    DUMMY_AUX_ATT_ARRAY : ARRAY [1..PMPS_GVL.AUX_ATTENUATORS] OF ST_PMPS_Attenuator;`

**Comment by klauer** [comment]
Interesting - glad to see it wasn't the nested comment that caused the failure like my dumb parser 😄

**Comment by slacAWallace** [comment]
Does it fail on every login with online change?

I really don't want to have to initialize these things...

**Comment by slacAWallace** [comment]
I suppressed the warning with some pragmas and am going to close this issue for now. Happy to take a look at a build that won't go online as a result of this issue.
