### ISSUE TITLE
Bypass override duration using date and time

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/lcls-twincat-pmps#81]
PMPS UI is ready, but the fast fault system needs to be changed to work with the date time representation, ideally in parallel with the ms representation.

**Comment by ghalym** [comment]
So an expiry date and time is selected from the UI?

**Comment by ghalym** [comment]
@ZLLentz I need some help understanding the requirement here. How is it implemented from the UI? Do we specify an expiry date and time? What is the epics pv record type?

**Comment by ghalym** [comment]
Thanks Zach, that was very helpful.

**Comment by ghalym** [comment]
Hello @ZLLentz, a PR is almost ready for this. I have one question though, is there a way from the UI to pick a date in the past? Should I add a check for it in the code?

**Comment by ghalym** [comment]
my worry if the plc system time is not right.
I should add the check anyway i guess.

**Comment by ZLLentz** [comment]
If the plc system time is not right we may have other issues with the input here, right? I wonder if there is a way we can validate the result...

**Comment by ZLLentz** [comment]
I've taken Hugo's UI work and resized things a bit in https://github.com/pcdshub/pmps-ui/pull/44.
I'll do the final steps of adjusting PVs/settings for absolute time once you're ready to do the PR here.
